nodes:
    - peerId: 12D3KooWEPvwLVBZaE8adsDoLh7QT9wrsw4PC82AdcDGYPgssNH7
      address: [ "any-sync-node-1:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs08DIQPUmLv2IiawramM4Ris8NHvmedA/9H9EcMizKmYH5zMoQdL5wfR+WQpsq746zt3MNAvUsq/oB9UbecpHahgHsqnX6sSq6txnUI6vyNExrSPMFd0g8aFbPwK6DWppa/ULWTNTkAsS1qU/EpfPKVHpwHpoWlgpsVxrqrK3JDz7ghilUDbtcUtIl0qzBxUILpBDySV0tfyugJAsqCE/brO81IDgNV+W3qKgu6Vs0wgPBG/iR//jjlkTsyzElEhqexSm6QMKYShZqa3J5EW+xlAW3NGJdF/Z6ddvBOa9BwSAHQ+kbzkeUd6CMxdLMOKDNCpTm7fyrp/oq0za7OtgwIDAQAB
      types:
        - tree
    - peerId: 12D3KooWFMZGP4Jp4uNgDKAjzFpoyYaHbpAVL2jMv9NdYJMFgaqp
      address: [ "any-sync-node-2:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwj8ZDMLGBxF1JeA0iT7wY80fKtr8Iv4q8Yt8TAXvM7Tkb9+dubO2CamWPmEHSyleJW8stG/JucVKJkNTZ52uqEpaJwq0M69k5xy5P0g2tFhucxPiJP9hr6S4k/1qxyAFGHTpHZ3tbeUTYivonkE3WIIOK3au/AL+CCuJSResfCdZ/YMgcvatCkS116nnNt7uoldcXDBnjUo6RRB4uRwqShDmG+iPanz8HpneqQNvVUUwfPfT0hgCeCmVEZHdmv793VzeSudmgyFjp7nm97vWZpivLS0F+5+xJ4K/h0Qdu8HIe7+dStJTXaMymeBpBCmGslp+LDVd6pjWrYa83UZ6iQIDAQAB
      types:
        - tree
    - peerId: 12D3KooWPQSfv8JbmwXv3QvcPQfSEuM2PujnMVXfcMojVgc5zGFD
      address: [ "any-sync-node-3:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt07voyAe3snEI4JfeN9tnh1FLP04zh949Rra637JNRclDj7inHeRdUFZr+0PVxrwkvVjwrl0Qe0j3xT1SLbXLLr0DZ4syAyB2uKL+n0ackFSKixPQB5NG20sJwen7l9tx7z9y/2OGqusECASd6Hrz+Z1N0Sww6juDcx32ItcyDhVN60+MUSBIOxr4g85kEAjU4nQiD4hahpKxyJb1wf2R1Ic3bi71kPrvP7jsXbOZrQhzSLBmQxMMF7LxAwqJgF/WtoDKsCSCACz2h+GU0Hx0NMJPi33Jyc+rgWAn03ENhumiEh4r9Yar+lcUG6XZ4hwmd9u4QaWT1E5DKsTLGsWAwIDAQAB
      types:
        - tree
    - peerId: 12D3KooWPUMFQFeiyZDwS2aGZJfcYZamwq3NLQJT6RskEzPfP2Xd
      address: [ "any-sync-coordinator:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4iy30MBtOzzZRzDyccwRLbJ0SBNUD8+yxNv0DsYegK1IHZFxSoj4CEPGXZpGDvKbzuFIy25i+wT0HCTgA+ioFr3usP+piQ8eEQeab2TG9cL/4TE+5Z/LAW96G/7twhJgTltjvgFRTv0i+OZEU5QBeIf2ykNa5Iy189eEnfuWm9JKvSSwTGlccQTjw3kPwv0MvaopiCB+T5gSSX5jW96gn+3SWPaGk9Up1WFhEgZWJg7XlHq9999tbpg7gCeRhljTGxA5iUeez1cU7jsIAiQLOE5Pc1fQ/tpKHBt7eCWjNHbHHFg/HUauvr4Uu9RQCnzV8tzynxJv1i+JTOxCTVTc9QIDAQAB
      types:
        - coordinator
    - peerId: 12D3KooWMwE15iEG51Sewt2zYqwgbrBz6QMuFVdWLBMes1SADtCh
      address: [ "any-sync-filenode:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvheEs4zUvPHxwnjY5pzTiagwvG2G8pb9fNZdiJKq3KD81QHCUOKuSbblp+bNeGsvcBJmEO3YuAk/Vwjc9P35TriW/6DUY1/qi5PDIH+V9XR41speDVHaTHtHlzatqCE11pDD1pY8E9O28kzZ0fGujsoGKoqPBETYEBTJZD9zgu6GHq2TKdtenca4kROVUwMV8RT1BOoa1T18ndQupkDcY+y7f8ov1eFM4uTg8Kqe64BuRs6NKe5Bh69RaAAOXVv4imqPY85MjKtOrWb4e2GcSLvbx3US1GnnEMPWIuL+Ma7hqB3PKsYRzECDuAqAvzPTDl65OewMYiuujfC4unQkBQIDAQAB
      types:
        - file
metric:
    addr: 0.0.0.0:8000

log:
    defaultLevel: ''
    namedLevels: {}
    production: false
account:
    peerId: 12D3KooWFMZGP4Jp4uNgDKAjzFpoyYaHbpAVL2jMv9NdYJMFgaqp
    peerKey: jYCOxScFFgBVpwc3x/hABTWOm8mA3Pgmtz+kZNf0XL5SR/zCPJCkXiWuYUlJHEXckqWQRgEwWwQNkYhWO+r96w==
    signingKey: jYCOxScFFgBVpwc3x/hABTWOm8mA3Pgmtz+kZNf0XL5SR/zCPJCkXiWuYUlJHEXckqWQRgEwWwQNkYhWO+r96w==
    encryptionKey: MIIEpAIBAAKCAQEAwj8ZDMLGBxF1JeA0iT7wY80fKtr8Iv4q8Yt8TAXvM7Tkb9+dubO2CamWPmEHSyleJW8stG/JucVKJkNTZ52uqEpaJwq0M69k5xy5P0g2tFhucxPiJP9hr6S4k/1qxyAFGHTpHZ3tbeUTYivonkE3WIIOK3au/AL+CCuJSResfCdZ/YMgcvatCkS116nnNt7uoldcXDBnjUo6RRB4uRwqShDmG+iPanz8HpneqQNvVUUwfPfT0hgCeCmVEZHdmv793VzeSudmgyFjp7nm97vWZpivLS0F+5+xJ4K/h0Qdu8HIe7+dStJTXaMymeBpBCmGslp+LDVd6pjWrYa83UZ6iQIDAQABAoIBAGLiokr3wL4KahvNBpGz48a6vpoffuoFgDEU9ELzZnFpLj2xlebakNpcZer9lCv0NERUU2rL2eLjh7rw3T3LbQWpTDnB3jjNmk15Nuj7RzYKKrgUsDRrefxjm79i6//Q0idAJQh5xEwEqRh6B+LAin9ZPgNsWOpcT5wzJaF7FsjgkDf377RwIByJW0U+d+F0z5QzQsRYV4poW0M62nJkIwwcxtn7dFmrWKOqFeDbzQRUPf599jw47EAzehP/Axfv9ypl5dblB4zLwFKQRrCxovTi690SGpy6dplzswf5aNAxz6SD0JEXrnYRpNyc1qkiWplkknRriEP7HylUvttj830CgYEA6xM15KOMkEnMKDfQOwS5X60i/DLV8ey9vf13d04OkCgfS3BiVtOqHaE57Tb/A8g5nXH3zpI8aLFP4jopPxmSExe/Ajn2pycrmJ8vevUERnttuBbyT5aZMk8b8HepdXr64DIRhNyNMLQ0SBHoSJCZd946lHdgNTgnUUeyvUE4hzcCgYEA04mA4l5tqSh6JpWfu0gry+Pw8a2299XJOJz37s0appl+PQNdSjDB7KOU5DuMQlxB2CBmoNRJUsqS7znFNeuu3gBBKIIFXKUs2tho9Q+0iLG0UxSeREHrh4on7mCu4qYekxkHVXLRfxhDhGgshlYDY0IqDtotlkYOkw9p4Ig+bD8CgYBpgkLTL1D8xhK7DmoIw1MMjWJBffOm1RJIvwYq5z8EFu4M5xFMVU5qZB3iyadmJC0v7KJD9kDk4IixSleO+cQli6fwsOFzHtKjevdNocFcfTO+x5XUgQyblwQ8RwkpMJx/mhlg37kDXi6FFnyCbVxkf7sdPgNRf7Wt9pdT+H0NuwKBgQCoO84lugWqp4dmEk8DqiUytWiVPJusRPkQLj48TCBq6N3t9jQGYfqIkZxDW1x0Fl1DXplgRRS/ZF4xJZfDB1p+MmOfrLBI+xBOSBhI9aGVqQaJoHcyP97qX6TcP0Y2+PiN8jTT70nPs2NW9Wabu+Jb2W4Le9cPkU3cBUEmEhTbDwKBgQCF/cIvFm1z/P4id/pApLVUBbLGkYtK7X/1VzsNHer/ZAETRydCNYcGw0/TP8o+lKN6yDFG43e8cSRerhlEtIq87j79mn6uqWM7SKEVb94j9prNFNElw2r/bVt3AbT3wVLPrHHZ01BpYOPGiT4NB+nhMMD799mEYXtBww6DHXrPjQ==

apiServer:
    server:
        listenAddrs:
            - 0.0.0.0:8080
    stream:
        maxMsgSizeMb: 256
        timeoutMilliseconds: 1000

space:
    gcTTL: 60
    syncPeriod: 600
storage:
    path: /storage

nodeSync:
    periodicSyncHours: 2
    syncOnStart: true

grpcServer:
    server:
        listenAddrs:
            - any-sync-node-2:443
    stream:
        maxMsgSizeMb: 256
        timeoutMilliseconds: 1000
