# syntax=docker/dockerfile:1
FROM python:3.13-alpine
WORKDIR /code
COPY docker-generateconfig/env-requirements.txt .
RUN pip install --no-cache-dir -r env-requirements.txt
ENTRYPOINT ["sh", "-c", "python docker-generateconfig/env.py && python docker-generateconfig/generateTemplate.py"]
