# syntax=docker/dockerfile:1
FROM python:3.11-alpine
RUN apk add --no-cache bash yq perl
WORKDIR /code
COPY docker-generateconfig/requirements.txt requirements.txt
RUN pip install -r requirements.txt
HEALTHCHECK \
    --start-period=3s \
    --retries=10 \
    --interval=5s \
    --timeout=3s \
    CMD echo 'HEALTHCHECK' | nc 127.0.0.1 8000 | grep -q HEALTHCHECK
ENTRYPOINT ["/code/docker-generateconfig/processing.sh"]
