# syntax=docker/dockerfile:1
FROM ghcr.io/anyproto/any-sync-tools

ARG TARGETARCH

RUN set -eux; \
    apt update; \
    apt install -y --no-install-recommends \
        bash \
        curl \
        ca-certificates \
        perl \
        python3 \
        python3-yaml \
        python-is-python3; \
    curl -L "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${TARGETARCH}" \
        -o /usr/local/bin/yq; \
    chmod +x /usr/local/bin/yq; \
    rm -rf /var/lib/apt/lists/*
WORKDIR /code
ENTRYPOINT ["bash", "/code/docker-generateconfig/init.sh"]
