# syntax=docker/dockerfile:1
FROM ghcr.io/anyproto/any-sync-tools:latest

WORKDIR /code

RUN apt update && \ 
    apt install -y python3 python3-pip && \
    pip3 install --no-cache-dir pyyaml

CMD ["sh", "-c", "any-sync-network create --auto --c docker-generateconfig/defaultTemplate.yml && python3 docker-generateconfig/persistentAccount.py"]
