# syntax=docker/dockerfile:1
FROM python:3.11-alpine
WORKDIR /code
COPY docker-generateconfig/requirements.txt requirements.txt
RUN pip install -r requirements.txt
ENTRYPOINT ["/code/docker-generateconfig/env-and-compose.py"]
