nodes:
    - peerId: 12D3KooWEPvwLVBZaE8adsDoLh7QT9wrsw4PC82AdcDGYPgssNH7
      address: [ "any-sync-node-1:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs08DIQPUmLv2IiawramM4Ris8NHvmedA/9H9EcMizKmYH5zMoQdL5wfR+WQpsq746zt3MNAvUsq/oB9UbecpHahgHsqnX6sSq6txnUI6vyNExrSPMFd0g8aFbPwK6DWppa/ULWTNTkAsS1qU/EpfPKVHpwHpoWlgpsVxrqrK3JDz7ghilUDbtcUtIl0qzBxUILpBDySV0tfyugJAsqCE/brO81IDgNV+W3qKgu6Vs0wgPBG/iR//jjlkTsyzElEhqexSm6QMKYShZqa3J5EW+xlAW3NGJdF/Z6ddvBOa9BwSAHQ+kbzkeUd6CMxdLMOKDNCpTm7fyrp/oq0za7OtgwIDAQAB
      types:
        - tree
    - peerId: 12D3KooWFMZGP4Jp4uNgDKAjzFpoyYaHbpAVL2jMv9NdYJMFgaqp
      address: [ "any-sync-node-2:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwj8ZDMLGBxF1JeA0iT7wY80fKtr8Iv4q8Yt8TAXvM7Tkb9+dubO2CamWPmEHSyleJW8stG/JucVKJkNTZ52uqEpaJwq0M69k5xy5P0g2tFhucxPiJP9hr6S4k/1qxyAFGHTpHZ3tbeUTYivonkE3WIIOK3au/AL+CCuJSResfCdZ/YMgcvatCkS116nnNt7uoldcXDBnjUo6RRB4uRwqShDmG+iPanz8HpneqQNvVUUwfPfT0hgCeCmVEZHdmv793VzeSudmgyFjp7nm97vWZpivLS0F+5+xJ4K/h0Qdu8HIe7+dStJTXaMymeBpBCmGslp+LDVd6pjWrYa83UZ6iQIDAQAB
      types:
        - tree
    - peerId: 12D3KooWPQSfv8JbmwXv3QvcPQfSEuM2PujnMVXfcMojVgc5zGFD
      address: [ "any-sync-node-3:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt07voyAe3snEI4JfeN9tnh1FLP04zh949Rra637JNRclDj7inHeRdUFZr+0PVxrwkvVjwrl0Qe0j3xT1SLbXLLr0DZ4syAyB2uKL+n0ackFSKixPQB5NG20sJwen7l9tx7z9y/2OGqusECASd6Hrz+Z1N0Sww6juDcx32ItcyDhVN60+MUSBIOxr4g85kEAjU4nQiD4hahpKxyJb1wf2R1Ic3bi71kPrvP7jsXbOZrQhzSLBmQxMMF7LxAwqJgF/WtoDKsCSCACz2h+GU0Hx0NMJPi33Jyc+rgWAn03ENhumiEh4r9Yar+lcUG6XZ4hwmd9u4QaWT1E5DKsTLGsWAwIDAQAB
      types:
        - tree
    - peerId: 12D3KooWPUMFQFeiyZDwS2aGZJfcYZamwq3NLQJT6RskEzPfP2Xd
      address: [ "any-sync-coordinator:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4iy30MBtOzzZRzDyccwRLbJ0SBNUD8+yxNv0DsYegK1IHZFxSoj4CEPGXZpGDvKbzuFIy25i+wT0HCTgA+ioFr3usP+piQ8eEQeab2TG9cL/4TE+5Z/LAW96G/7twhJgTltjvgFRTv0i+OZEU5QBeIf2ykNa5Iy189eEnfuWm9JKvSSwTGlccQTjw3kPwv0MvaopiCB+T5gSSX5jW96gn+3SWPaGk9Up1WFhEgZWJg7XlHq9999tbpg7gCeRhljTGxA5iUeez1cU7jsIAiQLOE5Pc1fQ/tpKHBt7eCWjNHbHHFg/HUauvr4Uu9RQCnzV8tzynxJv1i+JTOxCTVTc9QIDAQAB
      types:
        - coordinator
    - peerId: 12D3KooWMwE15iEG51Sewt2zYqwgbrBz6QMuFVdWLBMes1SADtCh
      address: [ "any-sync-filenode:443" ]
      encryptionPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvheEs4zUvPHxwnjY5pzTiagwvG2G8pb9fNZdiJKq3KD81QHCUOKuSbblp+bNeGsvcBJmEO3YuAk/Vwjc9P35TriW/6DUY1/qi5PDIH+V9XR41speDVHaTHtHlzatqCE11pDD1pY8E9O28kzZ0fGujsoGKoqPBETYEBTJZD9zgu6GHq2TKdtenca4kROVUwMV8RT1BOoa1T18ndQupkDcY+y7f8ov1eFM4uTg8Kqe64BuRs6NKe5Bh69RaAAOXVv4imqPY85MjKtOrWb4e2GcSLvbx3US1GnnEMPWIuL+Ma7hqB3PKsYRzECDuAqAvzPTDl65OewMYiuujfC4unQkBQIDAQAB
      types:
        - file
metric:
    addr: 0.0.0.0:8000

log:
    defaultLevel: ''
    namedLevels: {}
    production: false
account:
    peerId: 12D3KooWMwE15iEG51Sewt2zYqwgbrBz6QMuFVdWLBMes1SADtCh
    peerKey: kTZYumPO7MoEsU7ZyeNTLFgYaO3rGFEHk2qXJdqnV9O0DhMk/wdbgkwrbqtIpVH4Bkx7LPEHesTg3DfH4G524g==
    signingKey: kTZYumPO7MoEsU7ZyeNTLFgYaO3rGFEHk2qXJdqnV9O0DhMk/wdbgkwrbqtIpVH4Bkx7LPEHesTg3DfH4G524g==
    encryptionKey: MIIEogIBAAKCAQEAvheEs4zUvPHxwnjY5pzTiagwvG2G8pb9fNZdiJKq3KD81QHCUOKuSbblp+bNeGsvcBJmEO3YuAk/Vwjc9P35TriW/6DUY1/qi5PDIH+V9XR41speDVHaTHtHlzatqCE11pDD1pY8E9O28kzZ0fGujsoGKoqPBETYEBTJZD9zgu6GHq2TKdtenca4kROVUwMV8RT1BOoa1T18ndQupkDcY+y7f8ov1eFM4uTg8Kqe64BuRs6NKe5Bh69RaAAOXVv4imqPY85MjKtOrWb4e2GcSLvbx3US1GnnEMPWIuL+Ma7hqB3PKsYRzECDuAqAvzPTDl65OewMYiuujfC4unQkBQIDAQABAoIBADlmBpbkxnQLJnIPZYc1AZcGZzjuZZoox4ADhpivmNIn9lAnSNJ9sBzoEi6BvbdHvjo8A//GofLoL+0K6xU6/yWrDUVA/gDHvJ3Kz1enztMgCUDqOD4TYjRH4VUimIs1A/m3GrtX/+oIuqwtUnRXYtsQ243K6uZiF0+7xxfzJOD6ud6Tg6jv3T4WZLfS7YNUMKwy04BSM/qvOCUsnCM6BLb1kMKSw9I12wx3uRS5RLORHraiG1nDw9UpVtbFEkaeds1ZC3U+BW2Kghqmumdiaar+Q+pE2OKyv/UtoINSJUrWMmpFM58d3zTEXCMqQNsEBhuk/uWTybs4kfMAEhbCtQECgYEA38LS/LlU+eOtgXgcsp4Q+Y+3ORbjCsoEqX4CC17uO4V6cCLSxCNOETYC1GonIafd+g3hJLexjj7qvHX/+IA7aRk8qTx4zimRSHHo/d1pgIvxEkReau0TU5YQDbE8J0QQlGhC9+CkdxMpat1KH/aqzXtR6uYTXfqtvt4ziOXklkECgYEA2XrYPjuYVYOnT+GJQep+YY9CIaxdp9Q59x8WLf373TsYCkp15UMRHVkYrC6D4oUpALCa5jqzBcf4VzYFgVTEYeh7Qv67q5fEUyNAVf+4NuLJldLsLvQV2K1ufHtLNymztVfesou9HBENC/M1lRGxTetkU8KI9nKJKbZPe/1ThMUCgYA6Jf/8axE5K0Cgn50dkdQpdn6P2HHCEQOrJDLVz6KrVyGdWH9bNy2HbXjIyJlItr4JyGeUyiPbKmCH/0Y4xuIpisRn2m4ubUDzCZ8ZsdtD65oHPDspIFjgZOPhGwjdz2NbncihcABtbU5bFgy4R7rVUVHVcFriFk3mhwnvboa7wQKBgCz1RDa5QyiKatAMo79Ipo+sedNUOpgzOzhm6MLhOmvlh3a5Jd4bGzKh9IPDqeft9yf5Wkw13kRXrnL46/Jsf5xt3u1ek5VJboBxTR96Ga7e+yVJ0SFzvABq+egp5MamjEv0ukjWsmVW8QeDY5RJcAnXm4nlMUMhMlG5Kn1LRTSxAoGAG5k+0UhAwZiyw2n/2eI50Ds/B76qKta3ZK650uP1REY/hkMysvbVX/M03UVozaize9tQjJsnRYRzYBRGRydpv+5PdrWHJkuP+QMEyjQ1yjbAtfypL0dJCrGWsuDIyQ8lxE234y1shhHjnk84Af1YP4zPtgtMZWyxJkWwumBd9u8=

s3Store:
    bucket: anytype-dev-filenode
    maxThreads: 16
    profile: default
    region: eu-central-1

grpcServer:
    server:
        listenAddrs:
            - any-sync-filenode:443
    stream:
        maxMsgSizeMb: 256
        timeoutMilliseconds: 1000
